[error] sbt.librarymanagement.ResolveException: Error downloading com.holdenkarau:spark-testing-base_2.12:2.3.0_0.12.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/viveksingh/.ivy2/local/com.holdenkarau/spark-testing-base_2.12/2.3.0_0.12.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/holdenkarau/spark-testing-base_2.12/2.3.0_0.12.0/spark-testing-base_2.12-2.3.0_0.12.0.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error] 	at lmcoursier.CoursierDependencyResolution$$Lambda$4684/324718040.apply(Unknown Source)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2489/30492629.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.util.Tracked$$$Lambda$2315/1836919717.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2491/1066409585.apply(Unknown Source)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2485/956329382.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.util.Tracked$$$Lambda$2267/1172579909.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error] 	at sbt.Classpaths$$$Lambda$1217/1712666248.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at scala.Function1$$Lambda$914/516934601.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2155/1110618954.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.Execute$$Lambda$2172/133888201.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.Execute$$Lambda$2163/779179975.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2170/742473724.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading com.holdenkarau:spark-testing-base_2.12:2.3.0_0.12.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/viveksingh/.ivy2/local/com.holdenkarau/spark-testing-base_2.12/2.3.0_0.12.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/holdenkarau/spark-testing-base_2.12/2.3.0_0.12.0/spark-testing-base_2.12-2.3.0_0.12.0.pom
